# Global tuned configuration file.

daemon = 1
dynamic_tuning = 0
sleep_interval = 1
update_interval = 10
recommend_command = 1
reapply_sysctl = 1
default_instance_priority = 0
udev_buffer_size = 1MB
log_file_count = 2
log_file_max_size = 1MB
rollback = auto
profile_dirs = /usr/lib/tuned/profiles,/etc/tuned/profiles
startup_udev_settle_wait = 0
